import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Navbar from "./(components)/Navbar"
import FloatButtons from "./(components)/FloatButtons"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} relative w-full font-poppins flex flex-col justify-center items-center min-h-screen`}
      >
        <Navbar />
        
        <FloatButtons />
        {children}
      </body>
    </html>
  )
}
