import type { Metadata } from "next"
import "./globals.css"
import FloatButtons from "./(components)/FloatButtons"
import ProviderQuery from "@/utils/ProviderQuery"
import { AuthContextProvider } from "@/contexts/auth-context"
import Body from "./(components)/Body"
import { Inter } from "next/font/google"
import Footer from "@/components/shared/Footer"

export const metadata: Metadata = {
  title: "La dulce tradicion",
  description: "Generated by create next app"
}

const inter = Inter({ subsets: ["latin"] })
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} relative w-full font-poppins flex flex-col justify-center items-center min-h-screen`}
      >
        <Body>{children}</Body>
        <Footer />
      </body>
    </html>
  )
}
